### ISSUE TITLE
node_modules

### ISSUE THREAD

**Issue by missating** [lauragift21/MovieSearchApp#2]
I don't really know what the right or wrong thing is yet, about adding node_modules to your repo since it already has the package dependency file to run npm install. 
But on a project where you have many contributors would you want to always merge the node_modules? 
Check out these links I found, please tell me what you think afterward. 
https://www.quora.com/Should-I-put-node_modules-in-gitignore
https://stackoverflow.com/questions/11459475/should-i-check-in-node-modules-to-git-when-creating-a-node-js-app-on-heroku
https://github.com/Unitech/pm2/issues/622
To remove the node_modules then: 
http://www.patrickcatanzariti.com/2014/11/how-to-remove-node_modules-from-your-git-repo/

**Comment by lauragift21** [comment]
Thanks, I'll check the links out
